# Generated by Django 4.0.4 on 2022-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('phoneNUmber', models.CharField(default='', max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
    ]
