# Generated by Django 4.0.4 on 2022-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_driver_municipalagent_privateagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('paidAmount', models.FloatField(default=0, max_length=255)),
                ('object', models.CharField(default='', max_length=255)),
                ('paymentMethod', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
