# Generated by Django 4.0.4 on 2022-04-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentlog_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentLink', models.CharField(default='', max_length=255)),
                ('cost', models.FloatField(default=0, max_length=255)),
            ],
        ),
    ]
