# Generated by Django 4.0.4 on 2022-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carSerialNumber', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('date', models.DateField(default='')),
                ('fine', models.FloatField(default=0, max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('deadLine', models.DateField(default='')),
            ],
        ),
    ]
