# Generated by Django 4.0.4 on 2022-04-30 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_car_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.driver'),
        ),
    ]
