# Generated by Django 4.0.4 on 2022-04-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_car_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.car'),
        ),
    ]
