# Generated by Django 4.0.4 on 2022-04-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_violation_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(default='', max_length=255)),
                ('pricePerHour', models.FloatField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='parkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('nbPlaces', models.IntegerField(default=0, max_length=255)),
                ('nbAvailablePlaces', models.IntegerField(default=0, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='MunicipalityZone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.municipalityzone'),
        ),
        migrations.AddField(
            model_name='car',
            name='parkingLot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.parkinglot'),
        ),
    ]
