# Generated by Django 4.0.4 on 2022-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_municipalityzone_parkinglot_car_municipalityzone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='nbAvailablePlaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='nbPlaces',
            field=models.IntegerField(default=0),
        ),
    ]
