# Generated by Django 4.0.4 on 2022-05-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_remove_admin_user_ptr_remove_car_municipalityzone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carSerialNumber', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(default='', max_length=255)),
                ('pricePerHour', models.FloatField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('nbPlaces', models.IntegerField(default=0)),
                ('nbAvailablePlaces', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentLink', models.CharField(default='', max_length=255)),
                ('cost', models.FloatField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('phoneNUmber', models.CharField(default='', max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='MunicipalAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('workAddress', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='PrivateAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('workAddress', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('date', models.DateField(default='')),
                ('fine', models.FloatField(default=0, max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('deadLine', models.DateField(default='')),
                ('car', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='MunicipalityZone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.municipalityzone'),
        ),
        migrations.AddField(
            model_name='car',
            name='parkingLot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.parkinglot'),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('paidAmount', models.FloatField(default=0, max_length=255)),
                ('object', models.CharField(default='', max_length=255)),
                ('paymentMethod', models.CharField(default='', max_length=255)),
                ('driver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.driver'),
        ),
    ]
