# Generated by Django 4.0.4 on 2022-05-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='MunicipalityZone',
        ),
        migrations.RemoveField(
            model_name='car',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='car',
            name='parkingLot',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='municipalagent',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='privateagent',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='car',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='MunicipalAgent',
        ),
        migrations.DeleteModel(
            name='MunicipalityZone',
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
        migrations.DeleteModel(
            name='PaymentLog',
        ),
        migrations.DeleteModel(
            name='PrivateAgent',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
