# Generated by Django 4.0.4 on 2022-05-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='phoneNUmber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='phoneNUmber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='municipalagent',
            old_name='phoneNUmber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='privateagent',
            old_name='phoneNUmber',
            new_name='phoneNumber',
        ),
    ]
