# Generated by Django 4.0.4 on 2022-05-01 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_admin_password_alter_driver_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.driver'),
        ),
    ]
