# Generated by Django 4.0.4 on 2022-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='carSerialNumber',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
