# Generated by Django 4.0.4 on 2022-05-02 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_blocked_alter_car_carserialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tries',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
