# Generated by Django 4.0.4 on 2022-05-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_user_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='workAddress',
            field=models.CharField(default='', max_length=255),
        ),
    ]
