# Generated by Django 4.0.4 on 2022-05-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_admin_workaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='MunicipalityZone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipalityzone'),
        ),
        migrations.AlterField(
            model_name='car',
            name='parkingLot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parkinglot'),
        ),
    ]
