# Generated by Django 4.0.4 on 2022-05-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_municipalityzone_car_municipalityzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='municipalityZone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.municipalityzone'),
        ),
        migrations.AlterField(
            model_name='car',
            name='parkingLot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.parkinglot'),
        ),
    ]
