# Generated by Django 4.0.4 on 2022-05-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_admin_workaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
