# Generated by Django 4.0.4 on 2022-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_parkinglot_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalityzone',
            name='address',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
